[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/video-player.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"